version: '3.8'

services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    container_name: backend
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/home/app

volumes:
  postgres:
    name: postgres
